image: registry.gitlab.com/brigittarucz/examapp

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

env_setup:
  stage: build
  script:
    - npm install

testing:
  stage: test
  script:
    - npm run lint
    - npm run coverage

pages:
  image: registry.gitlab.com/kea-teachers/kea-development-environments-2021-1
  stage: deploy
  script:
    - cd ./pages
    - bundle exec jekyll build -d ../public/
  artifacts:
    paths:
      - public
  only:
    - master

