image: registry.gitlab.com/brigittarucz/examapp

services:
  - name: mariadb:latest

variables:
  MYSQL_DATABASE: techevents_users
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: root

connect:
  image: mysql
  script:
  - echo "SELECT 'OK';" | mysql --user=root --password=password --host=mariadb techevents_users


stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

env_setup:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script:
    - npm run coverage

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    # - master
    - app_integration