version: '3'


services:

  web:
    build: ./
    image: brigdocker/tech_app

  mariadb_dummy:
    container_name: mariadb_dummy
    build: ./integration/
    ports: 
      - "3308:3308"
    depends_on:
      - nodeapp
      - mariadb
    networks:
      - dbnet

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
        - ./database:/tmp/database
        - mariadb_data:/var/lib/mysql
    ports:
        - "3306:3306"
    env_file:
        - environment/mariadb.env
    command: mysqld --init-file="/tmp/database/techevents_users.sql"
    networks:
        - dbnet

  nodeapp:
    build: .
    restart: always
    expose:
        - "5000"
    command: tail -F anything
    deploy:
        replicas: 3
        restart_policy:
            max_attempts: 3
            condition: on-failure
    depends_on:
        - mariadb
    networks:
        - webnet
        - dbnet

  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
        - "8000:80"
    depends_on:
        - nodeapp
        - mariadb
    networks:
        - webnet

volumes:
  mariadb_data:

networks:
  dbnet:
    driver: bridge
  webnet:
    driver: bridge